import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Bell, ShieldCheck, X, Sparkles } from 'lucide-react'
import { notificationApi } from '../../api/client'
import toast from 'react-hot-toast'

export default function NotificationPermission() {
  const [showPrompt, setShowPrompt] = useState(false)

  useEffect(() => {
    // Check if permission has already been requested/set in local storage
    const promptStatus = localStorage.getItem('stepup-notif-prompt')
    if (!promptStatus) {
      // Show prompt 3 seconds after mounting
      const timer = setTimeout(() => setShowPrompt(true), 3000)
      return () => clearTimeout(timer)
    }
  }, []);

  const handleRequestPermission = async () => {
    try {
      // Mock Requesting permission
      if ('Notification' in window) {
        const result = await Notification.requestPermission();
        if (result === 'granted') {
          // Generate a mock FCM Token
          const mockFCMToken = 'fcm_tok_' + Math.random().toString(36).substr(2, 9) + '_stepup';
          await notificationApi.registerToken(mockFCMToken);
          toast.success('System Push Notifications enabled! 🔔');
        } else {
          toast.error('Notifications permission denied.');
        }
      } else {
        // Fallback for browsers that don't support it
        const mockFCMToken = 'fcm_tok_fallback_env_' + Math.random().toString(36).substr(2, 6);
        await notificationApi.registerToken(mockFCMToken);
        toast.success('Simulation: Push Notifications registered!');
      }
    } catch (err) {
      console.error(err);
      toast.error('Token registration failed.');
    } finally {
      localStorage.setItem('stepup-notif-prompt', 'done');
      setShowPrompt(false);
    }
  };

  const handleDismiss = () => {
    localStorage.setItem('stepup-notif-prompt', 'dismissed');
    setShowPrompt(false);
  };

  return (
    <AnimatePresence>
      {showPrompt && (
        <motion.div
          initial={{ opacity: 0, y: 30, scale: 0.95 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 20, scale: 0.95 }}
          className="fixed bottom-6 right-6 z-[100] max-w-sm w-full p-5 rounded-2xl border"
          style={{
            background: 'rgba(18,18,26,0.92)',
            backdropFilter: 'blur(16px)',
            borderColor: 'rgba(108,99,255,0.3)',
            boxShadow: '0 8px 32px rgba(0,0,0,0.6)',
          }}
        >
          <div className="flex items-start gap-4">
            <div className="w-10 h-10 rounded-xl bg-brand/10 border border-brand/20 flex items-center justify-center text-brand flex-shrink-0">
              <Bell size={20} className="animate-swing" />
            </div>
            
            <div className="flex-1 space-y-1">
              <h4 className="font-display font-black text-sm text-white flex items-center gap-1.5">
                Enable Study Push Alerts
              </h4>
              <p className="text-[10px] text-muted leading-relaxed">
                Receive daily streak warnings and exam schedule check-ins generated by ARIA Coach directly to your desktop.
              </p>
              
              <div className="flex gap-2.5 pt-3">
                <button
                  onClick={handleDismiss}
                  className="px-3 py-1.5 rounded-lg text-[10px] font-bold border border-border text-muted hover:text-white transition-all"
                >
                  Later
                </button>
                <button
                  onClick={handleRequestPermission}
                  className="btn btn-primary px-4 py-1.5 rounded-lg text-[10px] font-bold flex items-center gap-1"
                >
                  <ShieldCheck size={11} /> Enable Now
                </button>
              </div>
            </div>

            <button
              onClick={handleDismiss}
              className="p-1 rounded-lg text-muted hover:text-white hover:bg-white/5 transition-all"
            >
              <X size={13} />
            </button>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}
